apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
  namespace: assignment
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello from Kubernetes</title>
    </head>
    <body>
        <h1>Welcome to my web page!</h1>
    </body>
    </html>
